version: "3"
services: 
  csgo-scrim:
    build: .
    volumes: 
      - ./csgo-data:/home/steam/csgo-dedicated/
    network_mode: "host"
    environment: 
      - SRCDS_TOKEN=309E76122D3C7522154AC7513C51984E
      - SCRIM=true # Set false for a team structured config
